const SOCKET_MESSAGE = new Map({
    1:'store-onboarding1-results',
    2:'store-onboarding2-results',
    3:'store-onboarding3-results',
    4:'store-survey-results',
    5:'enter-matchmaking',
    6:'',
    7:'',
    8:'',
    9:'',
    10:'',
    11:'',
    12:'',
    13:'',
    14:'',
    15:'',
    16:'',
    17:'',
    18:'',

})

const surveyTopics = [
    "playing sports",
    "watching sports",
    "exercising",
    "dining out",
    "going to a museum",
    "art",
    "hiking",
    "gaming",
    "going clubbing or dancing",
    "reading",
    "watching tv",
    "going to the theater",
    "watching movies",
    "going to concerts",
    "music",
    "shopping",
    "doing yoga"
  ];